### PR TITLE
Adding a new section "integration-of-matomo-with-open-targets"

### PR DESCRIPTION
**Pull request by pieterlukasse**
...just like we have for cBioPortal.

### CODE REVIEW

**Comment by fedde-s** [comment]
We have never tested these instructions with Open Targets versions released to date, they assume a pull request that's currently waiting for review.

**Comment by fedde-s** [comment]
Additionally, I was initially a bit hesitant about whether maintaining instructions specific to a version of cBioPortal/Open Targets here rather than in respective automation repositories for those projects doesn't complicate maintenance, but I see that it does probably make sense for now given the focus of the tasks we work on.

**Comment by pieterlukasse** [comment]
let's merge this once https://github.com/opentargets/webapp/pull/305 is merged.

**Comment by Sjoerd-van-Hagen** [comment]
@fedde-s I think this one can be cleaned up? The PR that Pieter refers to in the last comment was never merged.

**Comment by fedde-s** [comment]
Yes, we recently discovered that this repo hasn't been properly maintained the way due to a miscommunication between the subteams; I should archive it until we find a second non-cBioPortal client that wants Matomo again. Then we'll have to design a generic repo again based on the client-specific one that we have been maintaining.

**Comment by Sjoerd-van-Hagen** [comment]
Is there anything here that we would potentially use then? Everything seems to be 2 years old. We can also just delete this if we do not use it anymore.

**Comment by fedde-s** [comment]
I don't know the state of all the repositories that were supposed to refer to this, so I don't know whether we're using it.

**Comment by fedde-s** [comment]
_Probably_ not though, and we might be able to reverse-engineer it with a few days of work based on forks?

**Pull request closed without merging**
